# -*- coding: utf-8 -*-
"""Untitled0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_XaJikmDg3K3gYt3dAKqzOmTxJGG1La
"""

import glob
import shutil
import os


def tumor_combiner_dir(src_list, dst_dir):
  for folder in src_list:
    for jpgfile in glob.iglob(os.path.join(src_list, "*.jpg")):
      shutil.copy(jpgfile, dst_dir)

  return dst_dir

def notumor_copy(src_list, dst_dir):
  for jpgfile in glob.iglob(os.path.join(src_dir, "*.jpg")):
    shutil.copy(jpgfile, dst_dir)
  return dst_dir